export *  from './Home';
export *  from './DetailProduct';
export *  from './Products';
export * from './RawMaterials';
export * from './CategoriesRawMaterials';
export * from './AddProduct.jsx';
export * from './UpdateProduct.jsx';
export * from './AddRawMaterial.jsx';
export * from './UpdateRawMaterial.jsx';
export * from './DetailRawMaterials.jsx';
export * from './Plantillas.jsx';
export * from './AddPlantilla.jsx';
export * from './UpdatePlantillas.jsx';
export * from './Ventas.jsx';
export * from './AddVenta.jsx';
export * from './Login.jsx'
export * from './ImportRawMaterials.jsx';
export * from './ListaDeCompras.jsx';
export * from './Configuracion.jsx';
export * from './Perfil.jsx';
export * from './Tareas.jsx';

